
typedef struct _VIDEO_MEDIA_TYPE
{
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} VIDEO_MEDIA_TYPE;

[
   // 인터페이스의 유일한 ID
   uuid(00000000-0000-0000-0000-123456789ABC),
   version(1.0)
]

interface InterfaceName
{
	typedef [context_handle] void*	TRANS_HANDLE;

    const long DEFAULT_ASYNC_DELAY        = 100;
    const short APP_ERROR                 = -1;
    const char* DEFAULT_PROTOCOL_SEQUENCE = "ncacn_ip_tcp";
    const char* DEFAULT_ENDPOINT          = "8765";

	TRANS_HANDLE Connect([in, string] char* szOutput);
	void Close([in, out] TRANS_HANDLE *ppTr);
	//TRANS_HANDLE HelloWorld([in, string] char* szOutput);

	int OpenNewSegFile([in] TRANS_HANDLE hTr, [in] int index);
	int CloseSegFile([in] TRANS_HANDLE hTr);

	void DoEncode([in] TRANS_HANDLE hTr);

	int SetVideoType(	[in] TRANS_HANDLE hTr, 
						[in, ptr] const VIDEO_MEDIA_TYPE* _guid,
						[in] __int64 fps,
						[in] int width,
						[in] int height);

	int SetPicturesData([in] TRANS_HANDLE hTr,
						[size_is(numbers), in] char pData[],
						[in] int numbers);

	int SetPictureInfo(	[in] TRANS_HANDLE hTr,
						[in] __int64 st,
						[in] __int64 et,
						[in] int data_len,
						[in] int bKeyFrame);

	//void AsyncFunc(handle_t hBinding, [in] int nAsychDelay);
	void AsyncFunc([in] TRANS_HANDLE hTr);

	int OpenCompressedData([in] TRANS_HANDLE hTr);
	void CloseCompressedData([in] TRANS_HANDLE hTr);
	int GetCompressedDataInfo([in] TRANS_HANDLE hTr, [out] __int64 *numbers);
	int GetCompressedData(	[in] TRANS_HANDLE hTr,
							[in] int nRead,
							[out] int *pSize,
							[in, out, size_is(nRead)] char pData[]);
}
